[build]
rustc-wrapper = "sccache"
rustflags = [
	"-C", "linker=clang",
	"-C", "link-arg=--ld-path=mold",
]

[target.x86_64-unknown-linux-musl]
rustflags = [
	"-C", "linker=clang",
	"-C", "link-arg=--ld-path=mold",
	"-C", "target-feature=-crt-static"
]

[target.armv7-unknown-linux-gnueabihf]
rustflags = [
	"-C", "linker=clang",
	"-C", "link-args=-fuse-ld=lld --target=arm-linux-gnueabihf"
]
