[build]
rustc-wrapper = "sccache"

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
	"-C", "link-arg=--ld-path=mold",
	"-C", "target-cpu=native"
]

[target.x86_64-unknown-linux-musl]
linker = "clang"
rustflags = [
	"-C", "link-arg=--ld-path=mold",
	"-C", "target-cpu=native",
	"-C", "target-feature=-crt-static"
]

[target.armv7-unknown-linux-gnueabihf]
linker = "clang"
rustflags = ["-C", "link-args=-fuse-ld=lld --target=arm-linux-gnueabihf"]
