# The socket address the scheduler will listen on. It's strongly recommended
# to listen on localhost and put a HTTPS server in front of it.
public_addr = "0.0.0.0:10600"

[server_auth]
type = "jwt_hs256"
secret_key = "ibBlrcZ05mPyJMw7H_PSCTGARL41LAPv80tR0DOaWpE"

[client_auth]
type = "token"
token = "A(|IuDJ|StmZqFW4VsbQs@)E)7yb,>CGH~7K,M.7XCM=^n]?3_`%@?P$~eG1wFx&"
